import LoginPage from "./pages/Login";
import SignupPage from "./pages/Signup";
import Home from "./pages/Home";
import CreateProduct from './pages/createProduct'
import MyProducts from "./pages/myProducts";
import Cart from "./pages/cart";
import ProductDetails from "./pages/productDetails";
import Profile from "./pages/profile";
import CreateAddress from "./pages/createAddress";
import SelectAddress from "./pages/SelectAddress";
export {LoginPage, SignupPage,Home,CreateProduct, MyProducts,Cart,ProductDetails,Profile,CreateAddress,SelectAddress};